[package]
name = "abbs-update-checksum"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
abbs-update-checksum-core = { path = "./abbs-update-checksum-core" }
eyre = "0.6"
walkdir = "2.5.0"
abbs-meta-apml = { git = "https://github.com/AOSC-Dev/abbs-meta-rs", package = "abbs-meta-apml", rev = "4a592937b44e8bb93103edd34eff384169a3248a" }

[workspace]
members = ["abbs-update-checksum-core"]
